# LambdaTest Configuration

# Project and folder configuration
project_id: "01KQCYTQE4ZW640BQHRDCKT3GK"
folder_id: "01KQCYTR8YNYZN77V8JMKDZCAH"

# Test Run configuration
assignee: 3274842
environment_id: 2

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
