# LambdaTest Configuration

# Project and folder configuration
project_id: "01KQCZ36E75QP5VKCSB9X1Z28H"
folder_id: "01KQCZ3ME6MW3BXP0DP4MPPZAC"

# Test Run configuration
assignee: 41319
environment_id: 155636

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
